# Generated by Django 3.2.11 on 2022-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snip',
            field=models.CharField(default='Click above for read more...', max_length=255),
        ),
    ]
