# Generated by Django 3.2.11 on 2022-05-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_snip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snip',
            field=models.CharField(default='Click above to read more...', max_length=100),
        ),
    ]
